### ISSUE TITLE
Fehler in der Doku: ASC_autoAstroModeMorningHorizon

### ISSUE THREAD

**Issue by christoph-morrison** [fhem/AutoShuttersControl#16]
In ASC_autoAstroModeMorningHorizon ist ein Fehler in der Doku: Da wird auf ASC_autoAstroModeEvening verwiesen, sollte aber ASC_autoAstroModeMorning sein.

**Comment by CoolTuxNet** [comment]
Ich danke Dir. Werde ich korrigieren.
