### ISSUE TITLE
ASC_expert kann nur auf 1 gesetzt werden, nicht auf 0

### ISSUE THREAD

**Issue by christoph-morrison** [fhem/AutoShuttersControl#17]
Aktuell kann _ASC_expert_ nur auf 1 gesetzt oder gelöscht werden. Das ist imho eher ein ungewohntes Verhalten und ggf. auch aus Gründen der Performance nachteilhaft (wenn Attribut fehlt muss eine zusätzliche Verzweigung mit dem Defaultwert abgearbeitet werden).

**Comment by CoolTuxNet** [comment]
Ist aber auch normal in FHEM. Attribute die man nicht braucht werden nicht gesetzt. Wenn ich expert nicht brauche lösche ich das Attribut oder es ist generell erst gar nicht gesetzt.
Ich sehe hier kein Handlungsbedarf

**Comment by christoph-morrison** [comment]
Es geht mir eher nicht darum etwas zu setzen was man nicht braucht, sondern das man einen komplett anderen Befehl braucht um was bereits gesetztes wieder zu deaktivieren.
Setzen mit `attr ASC ASC_expert 1`
Löschen aber mit `deleteattr ASC ASC_expert` anstelle von `attr ASC ASC_expert 0`

Halte ich für nicht besonders intuitiv.

Wenn man das mal automatisieren will, muss man eine Verzweigung und komplett unterschiedliche Befehle benutzen.

Ich insistiere nicht darauf, aber die Änderung ist ja marginal und macht die Benutzung intuitiver.

**Comment by CoolTuxNet** [comment]
Wir belassen es bitte so wie es ist. Das automatische setzen von Attributen ist nicht zu empfehlen und ich möchte diesen Unsinn nicht auch noch fördern.

Grüße

**Comment by christoph-morrison** [comment]
Du hast mich da echt falsch verstanden. Es geht nicht darum, dass das Attribut automatisch gesetzt werden soll, sondern dass ich den Wert nicht mehr ändern wenn `ASC_expert` mal gesetzt ist, sondern nur das Attribut komplett löschen kann, weil du als Auswahl nur 1 erlaubst. Wenn du schlicht `ASC_expert:1` zu `ASC_expert:0,1` definierst, dann kann man die üblichen Mechanismen über `attr` nutzen.

**Comment by CoolTuxNet** [comment]
> Wenn man das mal automatisieren will, muss man eine Verzweigung und komplett unterschiedliche Befehle benutzen.
> Du hast mich da echt falsch verstanden

Den oberen Satz habe ich verstanden wie er da steht, Du hast an ein automatisiertes setzen des Attributes gedacht. Also so habe ich das Verstanden.
Der einzige Sinn welcher das setzen einer 0 hat ist das man einen anderen Befehl zum deaktivieren des experten Attributes hat. Da deleteattr ASC_expert das selbe Verhalten im ASC Modul wie attr ASC_expert 0 hervorruft.
Ich bin der Meinung das man gerade das setzen von Attributen "Bewusst" machen soll. Es soll "schwierig" sein damit der User über das was er da macht nach denkt.
Wenn jemand es einfach haben will oder "automatisiert" dann kann er das durch "Wissen" machen in dem er direkt in den Hash schreibt. Dann muss er nicht mal speichern.
So zu mindest sehe ich das Handling eines Attributes.

**Comment by christoph-morrison** [comment]
Der obere Satz war ein Beispiel dafür wo so ein fehlender Wert ein Problem ist. Ich hab z.B. einen "Globaler Debug"-Dummy, den ich an- und ausschalten kann und der dann z.B. in `global` und anderen Modulen die das unterstützen das Debugging hochdreht - da müsste ich dann für ASC extra einen weiteren Case einbauen der statt `0` zu setzen halt das Attribut löscht. Das ist aber nur mein spezieller use case. Ich dachte eher an den Schnellklicker, der die Option in der Liste findet, den Expert-Modus aktiviert und ihn dann nicht mehr über den Mechanismus los bekommt, mit dem er ihn einstmal aktiviert hat.

Deshalb auch meine Anmerkung, dass das Verhalten von `ASC_expert` (und auch das von  `ASC_debug`, btw) inkonsistent zu anderen Modulen ist. Aber hey, ist dein Modul. Ich sehe nur den Sinn darin nicht, dass man die anschalten aber nicht mehr über den gleichen Mechanismus ausschalten kann. Übrigens hast du das in deinen anderen Modulen auch so gemacht (z.B. `debugJSON` in GardenaSmart) ;-)

**Comment by CoolTuxNet** [comment]
Jepp habe ich. Und bei anderen wieder so wie hier. Habe es nicht ganz sauber bisher durchgezogen :-)
Nicht falsch verstehen, ich bin immer für gute Diskussionen und lasse mich auch gerne umstimmen, aber hier sehe ich aktuell keine Notwendigkeit. Das Attribut soll auch kein Dauersetzer für User sein. Ist wirklich nur wenn es Probleme gibt gedacht und die haben sich Gottseidank gelegt.

Vielen Dank für Deine tolle Mitarbeit!

Grüße
