### ISSUE TITLE
ASC_shuttersDriveOffset

### ISSUE THREAD

**Issue by christoph-morrison** [fhem/AutoShuttersControl#18]
_ASC_shuttersDriveOffset_ sollte vielleicht eher _ASC_shuttersDriveDelay_ heißen, wenn nur ein Delay gesetzt werden können soll (nach hinten, nicht nach vorne).

**Comment by CoolTuxNet** [comment]
Würde namentlich eindeutiger sein. Aber dann müsste man OffsetStart auch ändern. Dann kann ich mir mal für einen Versionssprung merken.

**Comment by christoph-morrison** [comment]
SIehe #19. Wenn du das zu einer Hysterese umdefinierst kann Offset auch bleiben. Muss man halt entsprechend dokumentieren.

**Comment by CoolTuxNet** [comment]
Wir lassen den mal offen und ich hoffe mich bei der nächsten großen Versionsumstellung daran noch zu erinnern :-)
