### ISSUE TITLE
Fehlender Check für ASC_Drive_Offset

### ISSUE THREAD

**Issue by christoph-morrison** [fhem/AutoShuttersControl#19]
Es gibt keinen Sanity-Check für den Wert in _ASC_Drive_Offset_, man kann z.B. auch `10ab` übergeben (was imho auch durch die Checks in `setDriveCmd()` kommt).

```
 perl -e 'print int rand(10ab);'
 Bareword found where operator expected at -e line 1, near "10ab"
	 (Missing operator before ab?)
 syntax error at -e line 1, near "10ab"
 Execution of -e aborted due to compilation errors
```

**Comment by CoolTuxNet** [comment]
Also eine Prüfung auf nur numerische Werte sagst?

**Comment by christoph-morrison** [comment]
Ja, wüde ich machen. Wenn es nur ein Delay sein soll auch ob der Wert positiv ist, sonst kann man auch einen ... keine Ahnung was das Gegenteil von Verzögerung ist. Verfrühung? ... angeben. Oder halt als Hysterese umbeschreiben.

**Comment by CoolTuxNet** [comment]
Ich habe nun eine Prüfung ein gebaut.
