### ISSUE TITLE
Zwangsschliessung

### ISSUE THREAD

**Issue by Beetle2003** [fhem/AutoShuttersControl#21]
Request:

Ich würde es begrüssen, wenn es eine Funktion geben würde, welche ein offenes Rollo zu einem bestimmten Zeitpunkt zwangsschliesst.
Dieses habe ich derzeit mit DOIF umgesetzt, sodass um 24:00 Uhr das entsprechende Rollo schliesset ohne den Fensterkontakt zu beachten. 
Ich habe diese Funktion eingebaut, da ich des öfteren vergessen habe ein Fenster in der Nacht zu schliessen.

**Comment by CoolTuxNet** [comment]
Ich bin dafür dieses auch weiterhin über das DOIF zu regeln.
