### ISSUE TITLE
universelles "Interface" zum Eingreifen/Übersteuern 

### ISSUE THREAD

**Issue by stefanpflug** [fhem/AutoShuttersControl#22]
Es entstehen ja immer mal wieder sinnvolle Ergänzungswünsche zur Logikerweiterung, von denen ja auch einige bereits Beachtung gefunden haben oder umgesetzt wurden.
Nun wird es aber auch Wünsche geben, die für den Einzelnen eine sehr sinnvolle Ergänzung darstellen, für die breite Masse aber nicht unbedingt einen Mehrwert darstellen bzw. das Modul irgendwann völlig aufblähen (und den Author an den Rande des Nervenzusammenbruchs treiben).
 
Ich könnte mir vorstellen, dass eine universelle Möglichkeit zum eingreifen mit externer Logik das Modul auf Dauer besser aufstellt.

Angenommen es gäbe 3 weitere Readings pro Rollladen:
- "von ASC ermittelter Modus / Position"
- "manuelle Position"
 - "Sperre für Fahrten durch ASC Automatisierung

Darüber hätte jeder Interessierte die Möglichkeit zusätzliche Logik anzudocken ohne das Modul über Umwege auszutricksen. 
Das Modul kann im Hintergrund weiterarbeiten, führt aber durch die Sperre keine Fahrten mehr aus.

Ich versuche das mal anhand eines Beispieles zu erläutern:
Genutzt wird z.B. das ASC mit einer normalen Astro Steuerung, mit der Komfortfunktion bei Terrassentüren und der Privacy Funktion bei einigen Rollländen die zur Strasse hin liegen.
Bei den Unwetterwarnungen der letzten Woche möchte man nun aber verhindern, dass die Rollländen außerhalb der sicheren Position (voll geschlossen oder voll geöffnet) stehen bleiben.

Also möchte man vielleicht Privacy auf der der Windrichtung entgegengesetzten Seite aushebeln,
die Komfortöffnung statt auf 80% auf 100% durchführen oder oder oder (der individuellen Phantasie sind ja oft keine Grenzen gesetzt).

Der Vorschlag mit den Readings ist auch nur ein Schnellschuss und taugt eventuell nicht 100% um erweiterte Logik einzubinden. 
Eventuell lässt sich das besser mit einem Hook und einer Möglichkeit zum Triggern abbilden.

**Comment by CoolTuxNet** [comment]
Es gibt ab Version 0.9.x { ascAPIset() }
