### ISSUE TITLE
feature request: Beschattung von Räumen nach Innentemperatur

### ISSUE THREAD

**Issue by rejoe2** [fhem/AutoShuttersControl#26]
Wir haben hier eine große Fensterfront, an der die Jalousien sich befinden. Wenn im Winter die Sonne schräg steht, kommt die schön rein, und es wird nicht nur hell, sondern auch richtig warm :) . Gestern und vorgestern: fast zu warm ??? ... Und das, obwohl die Türe ziemlich offen war.
Du ahnst es: Es wäre klasse, wenn man einen Sensor angeben könnte, der die Beschattung ggf. auch abhängig von der Innentemperatur auslösen würde.
Meine Idee dazu: Im ASC-Device EIN Attribut anlegen, in dem alle relevanten Raumtemperaturen aufgelistet werden können.
Muster: room1:sensor_x[:!state-Readingname],room2:sensor_z[:!state-Readingname],...
Keine passende Raumangabe: nur nach der Außentemperatur.
Dabei gehe ich davon aus, dass über die Winkelangaben ja gut bestimmt werden kann, welcher Rollladen in dem Raum ggf. überhaupt relevant ist.

**Comment by CoolTuxNet** [comment]
Ab Version devel 0.6.19.11 gibt es die Möglichkeit pro Rollo einen TempSensor an zu geben.
