### ISSUE TITLE
blocking time morgens bei Öffnen des Fenster(kontakts) nicht beachten

### ISSUE THREAD

**Issue by rejoe2** [fhem/AutoShuttersControl#27]
Morgens machen wir dann schon mal das Fenster zum lüften auf. Bis vor einigen Tagen hat das ASC auch dahingehend zur Kenntnis genommen, dass der betr. Rollladen auf "Lüften" (bzw. comfort-Position) gefahren ist, jetzt nicht mehr, vermutlich, weil keine Stunde mehr zwischen Öffnen und Sonnenaufgang liegt (die blocking-Times stehen auf default).
Ohne jetzt im Detail alles schon vollständig durchschaut zu haben, was mit den blockingTimes zusammenhängt,  mal die Frage, ob das in dieser Situation allgemein Sinn macht. Beim Schließen ja (deswegen würde ich auch ungern den Wert ändern), aber auch beim Öffnen? 
https://forum.fhem.de/index.php/topic,92628.msg909387.html#msg909387

**Comment by CoolTuxNet** [comment]
Sollte erledigt sein. Einzig das manuelle Fahren wird noch berücksichtigt für WinRecOpen
