### ISSUE TITLE
Keine Events mehr (im FileLog) vorhanden

### ISSUE THREAD

**Issue by hvorragend** [fhem/AutoShuttersControl#38]
Mir ist aufgefallen, dass ASC keine Events mehr bspw. bei der Beschattung generiert. 
Die FileLogs sind diesbezüglich leer.

**Comment by CoolTuxNet** [comment]
Welches Event erwartest Du genau? Theoretisch sollte einzig von ASC aus das Event für den Status im Rollo als Reading kommen.

**Comment by hvorragend** [comment]
Ja. Genau das. Ich will darauf ein DOIF/Notify reagieren lassen. 
Im Forum hattest du auch bestätigt, dass auch bei dir die Events dazu nicht funktionieren.

**Comment by CoolTuxNet** [comment]
Jepp, Bin da auch dran. Aktuell aber ohne Plan

**Comment by CoolTuxNet** [comment]
Sollte schön länger gelöst sein :-)
