### ISSUE TITLE
Auswerten von "ASC_Roommate_Device" bei Beschattung 

### ISSUE THREAD

**Issue by steffenxx** [fhem/AutoShuttersControl#39]
Die Beschattungsfunktion von ASC fährt einen Rollo bei aktiver Beschattung in die Postion „ASC_Shading_Pos“.  Eine Auswertung von Anwesenheit wird nicht vorgenommen. Um den maximalen Beschattungseffekt zu erzielen müssten die entsprechenden Rollos ganz geschlossen werden (PCT=0). Ist jedoch jemand zu Hause möchte er/sie u.U. nicht in ganz dunklen Zimmern sitzen.  

Es gäbe aus meiner Sicht 2 Lösungsansätze:

**1.) Die Flexible**
Erweiterung des  Attributs „ASC_Shading_Pos“ auf 2 Attribute. 

ASC_Shading_Pos_home = Position die bei aktiver Beschattung angefahren wird, wenn mindestens ein ASC_Roommate_Device=home ist.

ASC_Shading_Pos_absent = Postion die bei aktiver Beschattung angefahren wird, wenn alle ASC_Roommate_Device=absent sind.

**2.) Die Einfache**
Ein neues Attribut das das Fahren auf pct=0 (zu) veranlasst

ACS_Shading_absent_pos = [on/off] (default = off) Wenn „on“ wird bei bei aktiver Beschattung und „absent“ aller in „ASC_Roommate_Device“ konfigurierten Personen, der Rollo ganz geschlossen. Unabhängig von dem Wert in „ASC_Shading_Pos“

(https://forum.fhem.de/index.php/topic,99980.1290.html)

**Comment by hvorragend** [comment]
Würde uns allen das nicht entgegenkommen, wenn man im Attribut Perl erlaubt?
Schau mal bei #40. Meine Anfrage würde das auch lösen. 
Und CoolTux hat den Vorteil, dass er dafür keine Set-Funktionen und Migrationscode erstellen muss.

**Comment by CoolTuxNet** [comment]
Siehe #40
