### ISSUE TITLE
ASC_Time_Up_Late_WE_Holiday or similar

### ISSUE THREAD

**Issue by hvorragend** [fhem/AutoShuttersControl#4]
Wir haben bereits die Möglichkeit, beim Hochfahren das Wochenende bzw. Urlaubszeiten zu berücksichtigen. Folgende Zeit-Attribute stehen aktuell zur Verfügung:

- ASC_Time_Up_Early _(Öffnen ab)_
- ASC_Time_Up_WE_Holiday _(Öffnen WE+Urlaub)_
- ASC_Time_Up_Late _(Öffnen bis)_

- ASC_Time_Down_Early _(Schließen ab)_
- ASC_Time_Down_Late _(Schließen bis)_

Wäre es nicht konsistenter, wenn man beim Up_Late auch WE+Urlaub berücksichtigt?
Macht es dann evtl. auch Sinn, bei Down_Early wie auch Down_Late das Wochenende getrennt steuern zu können?

Das wird natürlich heftig mit den vielen Attributen. Aber ganz speziell beim Hochfahren fehlt mir die WE-Unterscheidung beim Late-Zeitpunkt.

Beispiel:
- ASC_Time_Up_Early: **08:00**
- ASC_Time_Up_WE_Holiday: **09:00**
- ASC_Time_Up_Late: **08:30**

Hier sollen die Jalousien am WE erst um 09:00 Uhr hochfahren. Aber der eigentlich Late-Zeitpunkt liegt halt davor. 

Wenn man so richtig weit ausholen will, könnte man dann die Namensgebung der Attribute auch konsistenter gestalten. Hier ist dann jedoch die Abwärtskompatibilität nicht mehr gegeben.

- ASC_Time_Up_Early
- ASC_Time_Up_**Early**_WE_Holiday (geändert)
- ASC_Time_Up_Late
- ASC_Time_Up_Late_WE_Holiday

- ASC_Time_Down_Early
-  **ASC_Time_Down_Early_WE_Holiday** (neu)
- ASC_Time_Down_Late
-  **ASC_Time_Down_Late_WE_Holiday** (neu)

**Comment by CoolTuxNet** [comment]
Meine letzten Tests haben ergeben das die Zeit für WE Fahrten korrekt gesetzt werden auch wenn Hearly früher ist wie Hearly_Holiday.
Magst Du das bitte einmal testen?

Bisher gab es keine Anforderung das schließen der Rolläden am WE anders zu setzen.

**Comment by hvorragend** [comment]
Okay, das funktioniert.
ASC_Time_Up_Late_WE_Holiday war auf 08:30 Uhr
ASC_Time_Up_Late war auf 08:15 Uhr

Die Jalousien haben am Freitag um 08:15+Offset geöffnet. Ich weiß natürlich am morgigen Samstag erst, ob das dann auch entsprechend am WE funktioniert.

Ich persönlich komme damit klar. 

Ich dachte nur, dass dieses Feature für einige andere vielleicht irgendwann von Interesse sein könnte.

**Comment by CoolTuxNet** [comment]
:-) bring mir die User bloß nicht auf dumme Ideen

**Comment by hvorragend** [comment]
Hat auch am Wochenende geklappt. 

Die Jalousie ist um 08:15 Uhr (=ASC_Time_Up_Late) heruntergefahren und das obwohl ASC_Time_Up_Late_WE_Holiday auf 08:30 Uhr eingestellt war .
