### ISSUE TITLE
ASC_Shading_Pos als Reading und nicht als Attribut? Oder Perl erlauben?

### ISSUE THREAD

**Issue by hvorragend** [fhem/AutoShuttersControl#40]
Ich bräuchte mal deine Meinung, denn schließlich ist dieser Wunsch mit einer vermutlich größeren Änderung verbunden.

Könnte man das Attribut ASC_Shading_Pos entfernen und darauf ein Reading machen, welches man über Setter setzen kann?

Warum?
Weil man somit die Möglichkeit hat, über Notify/DOIF oder ähnlich den Wert zu verändern. Und das ohne das "rote Fragezeichen" hinterm SAVE-Button. :-)

(Hintergrund: Ich versuche über die Wettervorhersage den Wert zu beeinflussen.)

Das könnte vielleicht auch für das Issue #39 von Vorteil sein.

---

Alternativ:
Man erlaubt im Attribut Perl-Funktionen und kann so per ReadingsNum auf andere Quellen verweisen. Oder wer will kann im Attribut die ganze Berechnung vornehmen. Je nach Professionalität des Nutzers. :-)

**Comment by CoolTuxNet** [comment]
und wenn ich einen zweiten Wert für das Attribut zu lasse? Würden Dir 2 Werte basierend auf Anwesenheit reichen?

**Comment by steffenxx** [comment]
Ja, ich denke das wäre gut. Es geht ja im Grunde "nur" darum ob es in dem Raum hell oder dunkel ist, wenn beschattet wird.

**Comment by CoolTuxNet** [comment]
in der aktuellen Devel Version ist es Möglich Perlcode im Attribut zu verwenden
