### ISSUE TITLE
Anpassungen bei den Attributen für die Helligkeits- bzw. Beschattungssensoren

### ISSUE THREAD

**Issue by hvorragend** [fhem/AutoShuttersControl#41]
Hallo CoolTux,

ich finde die Zuordnung bzw. Konfiguration der Helligkeits-relevanten Attribute ein wenig unglücklich umgesetzt.

Seit v0.6.x möchte ASC den (normalen) Helligkeitssensor wie folgt haben:

`ASC_BrightnessSensor - DEVICE[:READING] WERT-MORGENS:WERT-ABENDS`

Bei der Beschattung reichen reine numerische Werte. Ohne Angabe des Sensors und des Readings:

```
ASC_Shading_StateChange_Cloudy
ASC_Shading_StateChange_Sunny
```

Bei der Beschattung wird also immer auch der Sensor genommen, der auch für die normalen Fahrten genutzt werden kann. 

---

**Vorschlag Nummer 1:**
_Und das wird dir nicht gefallen._ :-)
Könnte man ASC_BrightnessSensor wieder aufspalten und daraus zwei/drei Attribute machen? Somit könnte man die Werte auch wieder über readingsGroups anpassen.

**Vorschlag Nummer 2:**
_Und das wird mir nicht gefallen, da ich dann nicht mehr über readingsGroups die Werte anpassen kann._

Kann man ASC_Shading_StateChange_Cloudy&Sunny nicht zusammenfassen und auch um einen Sensor-Namen erweitern? Also die gleiche Syntax wie oben?
Damit wird es nicht nur konsistenter von der Schreibweise, sondern man könnte hierfür auch ein eigenes Device hinterlegen. Das fehlt mir nämlich ein wenig.

Ehrlich gesagt habe ich kein Problem mit vielen Attributen. Vor allem nicht, wenn diese per Default mit sinnvollen Werten gefüllt sind oder vielleicht sogar im globalen ASC-Device als Fallback hinterlegt sind. Das macht die Rollo-Devices schlanker, da man nur Abweichungen konfigurieren muss.

Ich persönlich störe mich halt an folgende Schreibweise:
`ASC_BrightnessSensor - DEVICE[:READING] WERT-MORGENS:WERT-ABENDS`

Das ist sicherlich seit 0.6.x zu spät zum meckern, aber nichtsdestotrotz ist die Angabe der Helligkeitswerte nicht einheitlich.

Lass und bitte vor dem Ändern irgendwelcher Code-Zeilen noch darüber sprechen. Ich bin mir selbst noch nicht ganz so sicher, was der bessere Weg ist. :-) Danke.

**Comment by CoolTuxNet** [comment]
Ich muß gestehen ich komme mit der Logik nicht klar. Wieso willst Du für Beschattung und Brightness Tag Nachtfahrt unterschiedliche Sensoren für ein und das selbe Rollo angeben.
Ich gebe direkt am Rollo einen Sensor an. Dieser ist dann gültig für dieses Rollo, sowohl für Brightness Tag und Nachtfahrt und für Beschattung.

**Comment by hvorragend** [comment]
Okay, das ist nachvollziehbar. 
Dieser Punkt war mir eigentlich auch gar nicht so wichtig.

Ich finde es nur merkwürdig, dass man an einer Stellen das Device und die Werte konfiguriert. Und an anderer Stelle nur die Werte speichert. 

Lass mal gut sein. Ich bin gerade ein wenig verwirrt und irgendwie lohnt sich die Arbeit nicht, überhaupt irgendetwas zu ändern.

Sorry.

**Comment by CoolTuxNet** [comment]
Ganz entspannt. Weißt ja bin für alle Vorschläge offen und höre sie mir gerne an.
