### ISSUE TITLE
Timer / Funktion für schließen vor Sonnenaufgang / bevor es hell wird.

### ISSUE THREAD

**Issue by D3ltorohd** [fhem/AutoShuttersControl#43]
Eine Frage, gibt es so eine Funktion, oder könnte man sowas vllt noch mit einbauen. Einen weiteren Timer den man setzten könnte, morgens in der früh.
Folgendes Problem, ich mache nachts die Rollos komplett hoch, damit frische kühle Luft ins Haus strömt, nur leider wacht man dann recht früh auf, weil es ja schon recht früh hell wird draußen, daher meine Idee, einen Timer, den ich für Rollos extra setzten kann, in denen sie noch mals runterfahren, z.b. um 4 Uhr morgens. Dann wäre es dunkel wenn die Sonne aufgeht und man kann in Ruhe weiter schlafen, grad für unsere kleinen wäre das super.

Grüße,

**Comment by CoolTuxNet** [comment]
Ich denke das dies ein Einzelfall darstellt wäre eine eigene Lösung hier besser angebracht. Einfach ein at anlegen und mit Filter arbeiten.
