### ISSUE TITLE
Privacy Position auch morgens

### ISSUE THREAD

**Issue by SGi99** [fhem/AutoShuttersControl#46]
Hinzufügen einer Option (z.B. attr ASC_PrivacyDownTime_beforMorningOpen ?), um die Privacy-Position auch frühmorgens anfahren zu können, wenn es draußen noch dunkel und drinnen aber schon hell ist und damit eine identische Situation wie abends gegeben ist.

**Comment by CoolTuxNet** [comment]
In der aktuellen Developer Version umgesetzt
