### ISSUE TITLE
Roommate berücksichtigen ohne automatischen Fahrzeiten (ASC_Mode_Down bzw. ASC_Mode_Up "off")

### ISSUE THREAD

**Issue by meier81** [fhem/AutoShuttersControl#48]
Hallo,

hatte im Forum mal angeregt ob man die Attribute ASC_Down und ASC_Up nicht um den Parameter off erweitert, zur Zeit ist es so wenn man über den Roommate z.B. abends die Rolläden im Kinderzimmer runterfahren möchte bzw. das ganze auch morgens wieder rückgängig macht muss man dazu die Attribute ASC_Mode_Down und ASC_Mode_Up auf always stellen, damit gelten aber auch die automatischen Fahrzeiten, gegeben über die Attribute ASC_Down und ASC_Up. Könnte man hier nun off wählen könnte man die automatischen Fahrzeiten deaktivieren.

**Comment by PhilippWeber86** [comment]
Gibt es doch, oder nicht?

**Comment by CoolTuxNet** [comment]
Ich denke er meint das die Rollos nur auf die Roommates hören ohne Timer Steuerung. Hier kann man überlegen ASC_Down auf roommate zu erweitern so das gar nicht mehr per Zeit sondern nur noch per Anwesenheit gesteuert wird.

**Comment by meier81** [comment]
@LeonGaultier So war das eigentlich gemeint, die Rollläden sollen nur auf den Roommate hören und nicht auf die Timer.
Habe folgendes Problem: Ich möchte an meinen Rollläden die Beschattungssteuerung haben, dies funktioniert auch einwandfrei. Zudem eine Blockierung über einen Drehgriffkontakt bezüglich Aussperrschutz, habe ich noch nicht kann das Modul aber schon. Jetzt geht es darum das die Rollläden fahren wenn die Kinder ins Bett gehen bzw. Mittagsschlaf machen, funktioniert ja auch mit dem Modul mit dem Roommates. Es geht mir nun eigentlich darum das die Rollläden nicht über Zeit bzw. Astro fahren sollen wenn keiner schlafen ist in dem Zimmer bzw. was mittlerweile auch ein Fall wäre das die Zeit- bzw. Astrofunktion nur aktiv ist bei Roommate gone/absent. Wenn ich das aber einstelle fährt mein Rollladen natürlich nicht mehr bei Roommate sleep.
Ich denke man bräuchte einen eigenen Parameter wie z.B. `ASC_Mode_Sleep`, dieser hat die Attribute `on` und `off`, damit kann man die Roommateauswertung bezüglich des Schlafenstatus auswerten, egal wie die Parameter `ASC_Mode_Down` und `ASC_Mode_Up` stehen. Zudem kann man dann auch weitere Kombinationen machen, wie z.B. automatisch fahren wenn keiner Zuhause ist oder einer schlafen geht.

**Comment by CoolTuxNet** [comment]
@meier81 
Kannst Du die Version aus dem Branch patch-roommate bitte einmal testen bei Dir.
Nach dem Neustart steht ASC_Down und ASC_up im Attribut userattr jeweils zweimal drin. Bitte versuche jeweils die Version welche nicht roommate enthält raus zu nehmen.
ASC_Up:time,astro,brightness
ASC_Down:time,astro,brightness

**Comment by CoolTuxNet** [comment]
ASC_Down und ASC_Up haben roommate bekommen. Damit werden keine Timer gestützten Fahrten mehr durch geführt
