### ISSUE TITLE
Roommate absent -> home ignorieren wenn ASC_Mode_Up / ASC_Mode_Down = always

### ISSUE THREAD

**Issue by PhilippWeber86** [fhem/AutoShuttersControl#49]
Wenn das Attribut ASC_Mode_Up / ASC_Mode_Down auf "always" steht, sollte beim Statuswechsel von absent/gone auf home keine Aktion ausgelöst werden (wenn Tag ist und ASC_Mode_Up = always bzw Nacht ist und ASC_Mode_Down = always).

**Comment by CoolTuxNet** [comment]
Warum nicht? Hast Du ein Beispiel wo sowas störend ist?

**Comment by PhilippWeber86** [comment]
Das bezieht sich auf die Erklärung aus
https://forum.fhem.de/index.php/topic,99980.msg963669.html#msg963669
Es geht darum, dass ich nur absent, gone und home bei den Roommates nutze. Wurde das Rollo jetzt in der Nacht manuell bewegt und ein vorher nicht anwesender Roommate kehrt heim, wird das Rollo in die ASC_Closed_Pos gefahren.
Anders herum gefragt, in welchem Fall ist es denn sinnvoll hier eine Aktion auszulösen? Wenn ASC_Mode_Down auf always steht, wurde das Rollo ja auf jeden Fall durch ASC heruntergefahren. Daher ist doch dann ein erneutes Herunterfahren beim heimkommen eines Rommates nicht erforderlich, oder übersehe ich hier etwas?
