### ISSUE TITLE
Manuelle Fahrten durch ASC nicht korrigieren lassen

### ISSUE THREAD

**Issue by hvorragend** [fhem/AutoShuttersControl#5]
Ich würde es begrüßen, wenn man ASC so konfigurieren könnte, dass manuell durchgeführte Korrekturen der Jalousiestände nicht durch ASC wieder überschrieben werden.

Es gibt massig Situationen, in denen dies vorkommen kann.

Beispiel:
ASC fährt abends die Jalousien herunter und es ist kein Partymodus gesetzt (bzw. konnte nicht gesetzt werden). Man möchte aber dennoch spontan aus dem Fenster schauen oder muss Holz reinholen. Oder man möchte einfach die Anzahl der Lüftungsschlitze im Rollladen korrigieren, da diese je nach Witterung unterschiedlich sein können. 
ASC korrigiert dann diese Fahrt und man hat plötzlich den Kopf unter der Jalousie. :-)

Die Möglichkeiten über ASC_BlockingTime.* sind insbesondere bei einer zyklischen Helligkeitstriggerung nicht ausreichend. 

Vorschlag:
Im ASC-Device ein SET "correctManualDrives" oder "forceExactPositions" mit on|off.

Der Bewohner ist dann natürlich dafür verantwortlich, die Jalousien entsprechend wieder herunterzufahren. Und wenn nicht, dann passen am nächsten morgen die Positionen ja auch wieder.

**Comment by CoolTuxNet** [comment]
Ich behalte es im Hinterkopf und werde mir mal Gedanken dazu machen.

**Comment by hvorragend** [comment]
Wieso ist das Ticket eigentlich geschlossen?
Sollten hier nicht die Ideen gesammelt werden?

**Comment by CoolTuxNet** [comment]
Ich ging davon aus das wir das Thema durch blockingAfterManual abgeschlossen hatten.

**Comment by hvorragend** [comment]
Ich habe das gerade noch einmal getestet. 

Es gibt anscheinend Unterschiede:
Korrigiert man nur geringfügig (hier waren es pct13 statt pct0), so greift ASC nicht ein. 

Fährt man die Jalousie aber wieder vollständig hoch, so übersteuert ASC das (bei mir nach 27min) und fährt wieder runter. 
ASC_BlockingTime_afterManual = 1200

2019-02-15_19:46:25 Jalousie manuell runter
2019-02-15_19:51:28 Brightness-Wert aktualisiert (unterschritten)
2019-02-15_20:09:28 Brightness-Wert aktualisiert (unterschritten)
2019-02-15_20:13:23 Jalousie durch ASC wieder runter
