### ISSUE TITLE
Fehler im Quellcode

### ISSUE THREAD

**Issue by PhilippWeber86** [fhem/AutoShuttersControl#51]
Ohne die genaue Funktion verstanden zu haben, glaube ich dass in Zeile 1554 + 1555 des Quellcodes ein Fehler ist. Hier die Passage:
`    return EventProcessingShadingBrightness( $hash, $shuttersDev, $events )
      unless (
        (
               $shutters->getModeDown eq 'brightness'
            or $shutters->getModeUp eq 'brightness'
        )
`
getModeDown / getModeUp kann niemals den Wert 'brightness' besitzen. Ich vermute, hier ist getUp / getDown gemeint.

**Comment by CoolTuxNet** [comment]
Vielen Dank für den Hinweis.

Grüße
