### ISSUE TITLE
Force Mode für selfDefense

### ISSUE THREAD

**Issue by TommyER1** [fhem/AutoShuttersControl#53]
Erweiterung des selfDefense

absent: nur Rollläden von geöffneten Türen und Fenster werden ab absent geschlossen
gone: alle Rollläden von geöffneten Türen und Fenster werden ab gone geschlossen

Zwei weitere Stati für ASC_Self_Defense_Mode: 

force_absent: alle Rollläden von Türen und Fenster werden bei absend und unanbhängig von zu oder offen geschlossen
force_gone: alle Rollläden von Türen und Fenster werden bei gone und unanbhängig von zu oder offen geschlossen

Ausnahme: ASC_Self_Defense_Exclude:on

**Comment by CoolTuxNet** [comment]
sollte nun gehen.
