### ISSUE TITLE
ASC_Shading_Angle_right und ASC_Shading_Angle_left zusammenfassen

### ISSUE THREAD

**Issue by eurofinder** [fhem/AutoShuttersControl#54]
ASC_Shading_Angle_right und ASC_Shading_Angle_Left im neuen Attribut ASC_Shading_Angle zusammenfassen. Werte für rechts und links mit Doppelpunkt getrennt angeben. Das Attribut ASC_Shading_Direcdtion kann dann entfallen.

**Comment by hvorragend** [comment]
Ich mag die Idee nicht. 
Damit legt man die readingsGroups zu drei Attributen lahm.

**Comment by hvorragend** [comment]
Andererseits zugegeben: 
Das sind keine Einstellungen, die man oft verändert. Aber das Argument zieht ja bei beiden Seiten. Ich verstehe den Hintergrund, aber stört das wirklich so sehr, um hier Programmieraufwand reinzustecken?

**Comment by OncaPretaBG** [comment]
Eine Erweiterung der Beschreibung wäre hilfreich für die, die das Paket innerhalb des Sonnenwendekreises oder auf der südlichen Hemnisphäre einsetzen. Mir war zunächst auch nicht klar das links die Ausrichtung zur aufgehenden Sonne meint. Der Blickwinkel fehlt, schau ich in das Fenster oder schau ich hinaus. Sollte man überlegen.

**Comment by CoolTuxNet** [comment]
Beide Attribute wurden inklusive Direction zusammen gefasst
