### ISSUE TITLE
Attribut für Shading, das Auskunft darüber gibt, ob es gerade bewölkt ist

### ISSUE THREAD

**Issue by eurofinder** [fhem/AutoShuttersControl#55]
Einführung eines weiteren Attributes ASC_Shading_Cloudy (boolean) pro Rollladendevice, das neben Parametern wie z.B. Temperatur und Helligkeit zusätzlich in der Shading-Abfrage berücksichtigt wird, wenn gesetzt und Wert true ist.

**Comment by CoolTuxNet** [comment]
Das sollte dich durch den Brightness Sensor abgedeckt werden. Nur wenn mal ein Wölkchen da ist will man ja nicht gleich entschatten. Sonst wären die Rollos nur am rumrödeln.
