### ISSUE TITLE
ASC_WindowRec mit mehreren Devices

### ISSUE THREAD

**Issue by roman1528** [fhem/AutoShuttersControl#59]
Wie schon im Forum beschrieben habe ich keine ThreeState-Sensoren aber dafür doppelflüglige Fenster und demendsprechend zwei einfache Fensterkontakte. Es geht also um die Vantilate_WindowOpen-Funktion.
Toll wäre es wenn man also mehrere Fensterkontakte angeben könnte (eventuell noch mit Verknüpfungswahl (oder/und)). Damit würde man erreichen, dass es egal ist, welche Seite des Fensters man öffnet, oder eben beide Seiten des Fensters öffnen muss damit/bevor der Rollladen in die Vantilate_Pos fährt.

**Comment by CoolTuxNet** [comment]
Dies sollte mit Hilfe von structure umgesetzt werden.
