### ISSUE TITLE
Korrekturfaktoren für berechnete Astrozeiten

### ISSUE THREAD

**Issue by eurofinder** [fhem/AutoShuttersControl#6]
Hallo,

ich habe jetzt mal das Modul ASC ausprobiert und komme damit gut zurecht.
Ich habe ein wenig mit den verschiedenen Möglichkeiten für "ASC_autoAstroModeEvening" gespielt.
Ich würde mich freuen, wenn sowohl für "ASC_autoAstroModeEvening" als auch für "ASC_autoAstroModeMorning" Korrekturfaktoren als Zahlenwerte angegebn werden könnten, die den berechneten Wert um den eingestellten Wert "verändern".
Voreingestellt ist der Wert 0 = keine Änderung.
Negative Werte reduzieren jeweils um n-Minuten, positive Werte addieren n-Minuten.

Ich kenne dies von der Tahoma-Box und würde es auch gerne hier nutzen.

Gruß
eurofinder

**Comment by CoolTuxNet** [comment]
Du kannst in beiden Fällen Horizon wählen und dann mittels AutoAstroMode...Horizon entsprechende Korrekturwerte von -9 bis 9 wählen.
Mehr ist leider nicht möglich.

**Comment by eurofinder** [comment]
Danke für die Rückmeldung.
Habe das gerade mal ausprobiert. Damit ist eine "Verschiebung" um jeweils ca. 7 Minuten möglich.
Passt für mich.
