### ISSUE TITLE
Rollaeden schliessen nicht/verspaetet  

### ISSUE THREAD

**Issue by reklawykSekuL** [fhem/AutoShuttersControl#6]
Nach einem Update auf Version 0.4.0.5  wurde beobachtet, dass einzelne Rollo's  nicht 
mehr mit den uebrigen Rollo's  herunter fuhren sondern verspaetet.

An den Attributen wurde nichts (manuell) geändert nach dem Update.

Im ASC Device und den Rollos  stand ASC_Drive_Offset=-1  und   ASC_Drive_OffsetStart=-1

Alle ASC_Drive_Offset=0  und   ASC_Drive_OffsetStart=0  gestellt  und alles funktioniert wieder wie gewohnt.

**Comment by LeonGaultier** [comment]
fix in new version 0.6.0
