### ISSUE TITLE
Zwei Stufen zu zwei Zeiten für Rolladen runter- bzw rauffahren

### ISSUE THREAD

**Issue by bernd-adam** [fhem/AutoShuttersControl#60]
Was ich möchte, dass sich der Rolladen zur Astrozeit auf eine Position < 100 bewegt. Und er soll erst später zu einer festgesetzten Zeit vollständig runtergefahren werden. Z.B. Rolladen fährt zum Sonnenuntergang auf 70% runter und um 22.00 Uhr dann auf 100%. Äquivalent wäre das am Morgen sinnvoll, Rolladen fährt zu einer festgelegten Zeit um 30% rauf und zur Astrozeit dann vollständig. Z.B. Um 06.00 Uhr fährt er 30% hoch und bei Sonnenaufgang dann vollständig.

**Comment by CoolTuxNet** [comment]
Alles was ich anbieten kann sind die Privacy Attribute welche noch mal ordentlich aufgebohrt worden sind. Man kann hier nun mit diversen Möglichkeiten spielen.
