### ISSUE TITLE
ASC_Time_Up_WE_Holiday not recognized after update

### ISSUE THREAD

**Issue by zucki8** [fhem/AutoShuttersControl#62]
Before the Update:
ASC_Time_Up_WE_Holiday was set to 9:00 and it was correctly shown in the readings on weekends or holidays. 

After the recent update (around three days ago) the shutters drove up at 8:00 on saturday. The readings show now 8:00 for the next astro event, and I cannot change this time anymore. No matter what time for  ASC_Time_Up_WE_Holiday I set, always 8:00 is used as next astro event time

**Comment by zucki8** [comment]
Remark: I have 8:00 as ASC_Time_Up_WE_Holiday on other shutters

**Comment by CoolTuxNet** [comment]
Kannst Du mir ein list von dem Rollo geben wo die WE Zeit nicht stimmt.

**Comment by zucki8** [comment]
Hallo Leon,

das muss ich erst wieder aufsetzen, da ich das Modul derzeit deaktiviert habe. Ich melde mich wieder, sobald ich genaueres weiß.

Viele Grüße,
Mathias

23. März 2020 11:08, "Leon Gaultier" <notifications@github.com (mailto:notifications@github.com?to=%22Leon%20Gaultier%22%20<notifications@github.com>)> schrieb:
	Kannst Du mir ein list von dem Rollo geben wo die WE Zeit nicht stimmt.
