### ISSUE TITLE
Geöffnete Fenster schließen bei absent

### ISSUE THREAD

**Issue by xerion3800** [fhem/AutoShuttersControl#64]
Es soll möglich sein, dass Rolläden mit <Fensterkontakt:**open**> und bei <rgr_Residents:**absent** > die betroffenen Rollläden automatisch geschlossen werden wenn "ASC_ShuttersPlace=window".

**Comment by CoolTuxNet** [comment]
Dies sollte bereits mit der SelDefense Funktion ohne Probleme gehen.

**Comment by xerion3800** [comment]
Nein leider nicht. Das funktioniert nur wenn "ASC_ShuttersPlace=terrace". ist, bei "window" keine Reaktion. Ich habe mir dank deiner Hilfe bei den Fenster die bei absent noch geöffnet sind geholfen, dass ich diese als terrace deklariert habe. Das hat aber den Nachteil das ich dann keine Ventilate Position mehr nutzen kann, da das Rollo immer ganz öffnet wird.
