### ISSUE TITLE
verschiedene Fragen

### ISSUE THREAD

**Issue by byterex** [fhem/AutoShuttersControl#67]
1) ist möglich am Abend bei Sonnenuntergang (mit Zeitkorrektur +/- Min) die Rollläden z.B. auf 80% runter zufahren, sodass man noch eine Sicht nach außen hat (Tageslichtrollläden) und um z.B. 23:00 komplett schließen?

2) ich verwenden das Modul und SteuerHW den [KLF200](https://wiki.fhem.de/wiki/Velux_KLF200) mit Somfy Motoren. Diese erlauben mehrere Geschwindigkeiten. z.B. `"set <Name> pct 75 SILENT"` Ist das möglich über ASC?

3) wäre möglich generell die Readings von KLF200 zu berücksichtigen. z.B. wenn Rollläden von der original Fernbedienung gesteuert wurden?

4) gibt es die Einstellung, dass eine Rollläde nicht runter zu fahren, wenn eine Tür offen ist. Sobald die Tür geschlossen wird, sollte mit Verzögerung die Rollläde zu dem Prozent, welche zu dieser Zeit eingestellt ist, geschlossen werden. 

5) Kann ich Markize bei Wind und/oder Regen (Sensoren vorhanden) automatisch schliessen lassen?

Vielen Dank!

**Comment by CoolTuxNet** [comment]
1. JEIN, Es ist möglich eine gewisse Zeit vor Sonnenuntergang das Rollo in eine bestimmte Position zu fahren. PrivacyMode nennt sich das. Du kannst im Attribut die Zeit angeben vor dem in die PrivacyPosition gefahren werden soll bevor die Rollos komplett schließen.
Zum Beispiel:
ASC_PrivacyDownValue_beforeNightClose 1800
Fährt das Rollo eine halbe Stunde vor dem eigentlichen schließen in eine PrivacyPosition. Zum Beispiel 50%

2. NEIN

3. NEIN. Das Modul ist für eine generelle automatisierte Rollosteuerung ausgelegt. Daher darf sie nicht speziell für einen bestimmten Typ sein.

4. Ja gibt es. Es gibt das Attribut ASC_LockOut in Zusammenhang mit dem Attribut ASC_ShuttersPlace welches man auf terrace stellt. Dann fährt das Rollo gar nicht.

5. Ja das geht. Dazu muss alles andere an Steuerung bezüglich ASC deaktiviert werden und nur die Windsteuerung entsprechend mit Attribute gesetzt werden.

Ich finde solche Fragen gehören eher ins Forum und nicht als Issues hier her.

**Comment by byterex** [comment]
1. hmmm, würde reichen

2. warum machst du den Befehl für up/down nicht konfigurierbar, dann ist man systemunabhängig, zb dass man Perl code für up/down hinterlegen kann.

3. schade, weil hier einige User mit dieser HW gibt

4. hab nicht ganz verstanden, aber wenn du sagst, dass es geht, dann werde ich ausprobieren

ich habe die Punkte als feature requests hier geschrieben und auch weil im FHEM Forum 3 große Threads bereits geschlossen sind und keine weitere Antworten möglich sind. Und dort gibt es auch ein Verweis hier die Wünsche zu äussern.
Vielen Dank!
