### ISSUE TITLE
_IsDay: getModeDown/Up vs. getDown/Up

### ISSUE THREAD

**Issue by gnampf1** [fhem/AutoShuttersControl#68]
Ich hatte das Fehlverhalten meiner Terassentürrollade am Wochenende schon [hier](https://forum.fhem.de/index.php/topic,109366.msg1033556.html#msg1033556) beschrieben, am Wochenende fährt die Rollade bei Überschreiten der Brightness hoch, aber sobald vom Türschalter das Closed-Event kommt wieder runter mit "window closed at night". Passiert nur am Wochenende.

Ich vermute das Problem liegt in _IsDay bei:
```
    if (
        (
               $shutters->getModeDown eq 'brightness'
            or $shutters->getModeUp eq 'brightness'
        )

```
ASC_ModeDown und ASC_ModeUp kennen den Wert brightness eigentlich gar nicht, ich vermute hier müsste eher getDown / getUp verwendet werden?

**Comment by CoolTuxNet** [comment]
Danke Dir. Ich schaue es mir gerne an.

**Comment by CoolTuxNet** [comment]
Ich habe es gefixt. Kommt morgen per Update
