### ISSUE TITLE
ASC_ComfortOpenPos 0 deaktiviert ComfortOpen

### ISSUE THREAD

**Issue by gnampf1** [fhem/AutoShuttersControl#69]
Einen hab ich noch ;-) Wenn man ASC_ComfortOpen_Pos auf 0 setzt (bei ASC 1), dann ist ComfortOpen außer Kraft gesetzt und die Rollade fährt nicht mehr hoch. Setzt man einen Wert > 0 (1 reicht schon) funktioniert es wieder richtig, außer das die Rollade ggf. nicht komplett hoch fährt

**Comment by CoolTuxNet** [comment]
Das ist korrekt. Es müssen für jede Positionsangabe immer unterschiedliche Werte genommen werden. 0 ist schon belegt durch ganz oben (offen) oder ganz unten (geschlossen)

**Comment by gnampf1** [comment]
ganz offen wäre aber ja gewünscht in dem Fall, die Rollade soll doch komplett hochfahren wenn ich die Tür weit öffne (im Gegensatz zu kippen, das ist ja eine andere "Schalterstellung"). Als ich noch ASC 2 eingestell hatte gabs mit 100 auch keine Probleme. Oder versteh ich das Feature falsch?
ASC_ComfortOpen_Pos sollte dann ja auch 0 und 100 gar nicht in der Auswahlliste haben?

**Comment by CoolTuxNet** [comment]
Du kannst 1 nehmen das sollte gehen. Wieso es bei 100 gegangen sein soll kann ich mir nicht erklären. Zur Erkennung welcher Grund für die aktuelle Position des Fensters besteht wird die Position selbst ermittelt. Daher pro Position immer unterschiedliche Werte.
Das mit nicht 0 und nicht 100 kann man nur schwer jetzt noch ändern.

**Comment by gnampf1** [comment]
alles klar, muß man im Endeffekt nur wissen. Am besten 0 und 100 dann aus der Auswahl streichen und z.B. durch 1 und 99 ersetzen? Dürfte dann im Endeffekt eh kein Unterschied spürbar sein bei den meisten.
