### ISSUE TITLE
New attribute: ASC_ForceDrives (or similar)

### ISSUE THREAD

**Issue by hvorragend** [fhem/AutoShuttersControl#71]
Ich habe speziell bei Z-Wave-Aktoren ganz oft das Problem, dass die Positionsdaten der vorherigen Fahrt nicht zurückübermittelt werden. Obwohl ich schon per DOIF alle zwei Stunden die Werte hole, kommt es gelegentlich zu Fehlern. ASC denke, es müsste nicht fahren, weil laut FHEM das Rollo noch oben ist.

Könnte man ein Feature hinzufügen, dass auf die vorherigen Positionen keine Rücksicht genommen wird? Attribut "ASC_ForceDrives " oder ähnlich?

**Comment by CoolTuxNet** [comment]
Das würde nichts bringen, da an ganz vielen Stellen im Code immer die aktuelle Position abgefragt wird. So zum Beispiel bei der Beschattung oder bei Fensterevents

**Comment by hvorragend** [comment]
Schade
