### ISSUE TITLE
Verzögerung beim automatischen Runterfahren

### ISSUE THREAD

**Issue by lordofweb19** [fhem/AutoShuttersControl#72]
Folgender Ablauf funktioniert korrekt:
1) Nachts wird das Rollo manuell hochgefahren (z.B. zum Lüften)
2) Der Fenster-Sensor meldet "open".
3) Das Fenster wird geschlossen
4) Der Fenster-Sensor meldet "close"
5) Das Rollo fährt runter.

Was noch fehlt:
Zwischen den Schritten 4 und 5 sollte man einen Verzögerungswert konfigurieren können, z.B. um das Fenster korrekt zu schließen. Aktuell muss man sich sehr beeilen, da das Rollo sofort nach dem Kontakt mit dem Fenster-Sensor losfährt.

Warum ist es notwendig?
Das Rollo sitzt innen (IKEA), d.h. es ist wichtig, dass das Fenster geschlossen und der Griff in der korrekten Position ist. Sonst drohen böse Unfälle, wenn das Fenster doch wieder ein Stück aufgeht und das Rollo hängen bleibt.

**Comment by CoolTuxNet** [comment]
Ich kann bei meinen Fensterkontakt eine Verzögerung bezüglich der Meldung einstellen, geht das bei Dir auch? Was für einen Fensterkontakt hast Du?


Grüße

**Comment by lordofweb19** [comment]
In dem Fall ist es ein HM-Sec-SC-2 (Homematic)

**Comment by CoolTuxNet** [comment]
Das sollte da gehen. Leider habe ich mein FHEM abgebaut und somit auch die Kontakte. Bitte informiere Dich wie man hier die Verzögerung per Register setzt
