### ISSUE TITLE
Rollo fährt nachts wieder hoch wenn Shading aktiviert ist

### ISSUE THREAD

**Issue by lordofweb19** [fhem/AutoShuttersControl#73]
Am ASC_Device ist controlShading = on gesetzt. Außerdem ist ein twilight-Device und ein Temperatur-Sensor gesetzt.

Am Rollo ist gesetzt:
ASC Down ist auf astro gesetzt, die Zeiten Early/Late für Down sind korrekt eingetragen. Die Werte für Brightness, Temperatur, Azimuth und Elevation sind vermutlich korrekt, da das Rollo tagsüber zu den erwarteten Werten auch wirklich runter fährt.
Aber nachts wird das zum Problem: Das Rollo fährt runter und nach der "shading blocking time" wieder hoch mit der Shading-Info "Out". Es ist schon klar, dass nachts nicht beschattet werden muss, aber wenn sich die Uhrzeit nach dem "night close" befindet, dann sollte das Rollo unten bleiben, auch wenn nicht mehr beschattet werden muss.

Workaround:
Am ASC-Device controlShading = off setzen jeden Abend => etwas nervig

**Comment by CoolTuxNet** [comment]
Un spätestens hier wäre nun eine Versionsangabe schick. Denn diesen Bug hatte ich eigentlich noch in der alten 0.8er Version gefixt.

**Comment by lordofweb19** [comment]
FVERSION | 73_AutoShuttersControl.pm:v0.10.3-s22366/2020-07-07 TESTING
VERSION | v0.10.3

**Comment by CoolTuxNet** [comment]
Ich habe gerade geschaut. Laut Code dürfte es nicht so sein. Kannst Du bitte ein list vom ASC Device und dem betroffenen Rollo Device posten.

**Comment by lordofweb19** [comment]
Reicht das so oder soll es in einer Situation sein, wo das Rollo hätte eigentlich durch "night close" zu sein müssen?

### ASC_Device
Internals:
   FUUID      5e8059eb-f33f-a573-bdb8-15fb75fd15820042
   FVERSION   73_AutoShuttersControl.pm:v0.10.3-s22366/2020-07-07 TESTING
   MID        da39a3ee5e6b4b0d3255bfef95601890afd80709
   NAME       rolloControl
   NOTIFYDEV  global,rolloControl,HUEDevice65539,HUEDevice65544,HUEDevice65556,HUEDevice65562,HUEDevice65565,sonnenstand,Flower5D4A,HmIP_SLO_000D5A49A83946,HUEDevice65544,HUEDevice65556,HUEDevice65547,HUEDevice65562,HM_718426,HM_4E1E2E,HUEDevice65539,HUEDevice65565,ASC_WindowRec_PosAfterDayClosed,HM_36CD57
   NR         516
   NTFY_ORDER 51-rolloControl
   STATE      shading in
   TYPE       AutoShuttersControl
   VERSION    v0.10.3
   OLDREADINGS:
   READINGS:
     2020-07-10 09:40:30   HUEDevice65539_PosValue 10
     2020-07-06 08:11:03   HUEDevice65539_lastDelayPosValue 10
     2020-07-10 09:40:04   HUEDevice65539_lastPosValue 100
     2020-07-10 08:00:02   HUEDevice65539_nextAstroTimeEvent 10.07.2020 - 21:26
     2020-07-10 07:45:28   HUEDevice65544_PosValue 100
     2020-07-09 21:27:36   HUEDevice65544_lastDelayPosValue 30
     2020-07-10 07:45:02   HUEDevice65544_lastPosValue 0
     2020-07-10 07:45:02   HUEDevice65544_nextAstroTimeEvent 10.07.2020 - 21:26
     2020-06-09 12:54:15   HUEDevice65547_PosValue 100
     2020-05-07 07:00:02   HUEDevice65547_lastDelayPosValue 100
     2020-05-22 07:00:02   HUEDevice65547_lastPosValue 2
     2020-07-10 07:00:36   HUEDevice65556_PosValue 100
     2020-06-08 07:00:02   HUEDevice65556_lastDelayPosValue 100
     2020-07-10 07:00:02   HUEDevice65556_lastPosValue 0
     2020-07-10 07:00:02   HUEDevice65556_nextAstroTimeEvent 10.07.2020 - 21:26
     2020-07-10 07:54:01   HUEDevice65562_PosValue 0
     2020-06-27 21:32:36   HUEDevice65562_lastDelayPosValue 100
     2020-07-10 07:45:02   HUEDevice65562_lastPosValue 0
     2020-07-10 07:45:02   HUEDevice65562_nextAstroTimeEvent 10.07.2020 - 21:26
     2020-07-10 07:00:36   HUEDevice65565_PosValue 100
     2020-07-10 07:00:02   HUEDevice65565_lastPosValue 0
     2020-07-10 07:00:02   HUEDevice65565_nextAstroTimeEvent 10.07.2020 - 21:26
     2020-03-29 10:39:16   ascEnable       on
     2020-07-10 08:04:28   controlShading  on
     2020-03-29 10:18:51   hardLockOut     off
     2020-06-08 10:21:12   partyMode       off
     2020-07-09 19:38:25   room_Arbeitszimmer HUEDevice65539
     2020-07-09 19:38:25   room_Kueche     HUEDevice65556,HUEDevice65565
     2020-07-09 19:38:25   room_Schlafzimmer HUEDevice65544
     2020-07-09 19:38:25   room_Wohnzimmer HUEDevice65562
     2020-03-29 10:18:51   selfDefense     off
     2020-07-10 09:40:30   state           shading in
     2020-03-29 10:35:17   sunriseTimeWeHoliday on
     2020-07-09 19:38:25   userAttrList    rolled out
   helper:
     shuttersList:
       HUEDevice65539
       HUEDevice65544
       HUEDevice65556
       HUEDevice65562
       HUEDevice65565
   monitoredDevs:
     ASC_WindowRec_PosAfterDayClosed:
       HUEDevice65539 userattr ASC_Adv:on,off ASC_Antifreeze:off,soft,hard,am,pm ASC_Antifreeze_Pos:5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100 ASC_AutoAstroModeEvening:REAL,CIVIL,NAUTIC,ASTRONOMIC,HORIZON ASC_AutoAstroModeEveningHorizon:-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9 ASC_AutoAstroModeMorning:REAL,CIVIL,NAUTIC,ASTRONOMIC,HORIZON ASC_AutoAstroModeMorningHorizon:-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9 ASC_BlockingTime_afterManual ASC_BlockingTime_beforDayOpen ASC_BlockingTime_beforNightClose ASC_BrightnessSensor ASC_Closed_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_ComfortOpen_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_Down:time,astro,brightness,roommate ASC_DriveUpMaxDuration ASC_Drive_Delay ASC_Drive_DelayStart ASC_ExternalTrigger ASC_GuestRoom:on,off ASC_LockOut:soft,hard,off ASC_LockOut_Cmd:inhibit,blocked,protection ASC_Mode_Down:absent,always,off,home ASC_Mode_Up:absent,always,off,home ASC_Open_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_Partymode:on,off ASC_Pos_Reading ASC_PrivacyDownValue_beforeNightClose ASC_PrivacyDown_Pos ASC_PrivacyUpValue_beforeDayOpen ASC_PrivacyUp_Pos ASC_RainProtection:on,off ASC_Roommate_Device ASC_Roommate_Reading ASC_Self_Defense_AbsentDelay ASC_Self_Defense_Mode:absent,gone,off ASC_Shading_InOutAzimuth ASC_Shading_MinMax_Elevation ASC_Shading_Min_OutsideTemperature ASC_Shading_Mode:absent,always,off,home ASC_Shading_Pos:10,20,30,40,50,60,70,80,90,100 ASC_Shading_StateChange_SunnyCloudy ASC_Shading_WaitingPeriod ASC_Shutter_IdleDetection ASC_ShuttersPlace:window,terrace ASC_Sleep_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_TempSensor ASC_Time_Down_Early ASC_Time_Down_Late ASC_Time_Up_Early ASC_Time_Up_Late ASC_Time_Up_WE_Holiday ASC_Up:time,astro,brightness,roommate ASC_Ventilate_Pos:10,20,30,40,50,60,70,80,90,100 ASC_Ventilate_Window_Open:on,off ASC_WiggleValue ASC_WindParameters ASC_WindProtection:on,off ASC_WindowRec
       HUEDevice65544 userattr ASC_Adv:on,off ASC_Antifreeze:off,soft,hard,am,pm ASC_Antifreeze_Pos:5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100 ASC_AutoAstroModeEvening:REAL,CIVIL,NAUTIC,ASTRONOMIC,HORIZON ASC_AutoAstroModeEveningHorizon:-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9 ASC_AutoAstroModeMorning:REAL,CIVIL,NAUTIC,ASTRONOMIC,HORIZON ASC_AutoAstroModeMorningHorizon:-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9 ASC_BlockingTime_afterManual ASC_BlockingTime_beforDayOpen ASC_BlockingTime_beforNightClose ASC_BrightnessSensor ASC_Closed_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_ComfortOpen_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_Down:time,astro,brightness,roommate ASC_DriveUpMaxDuration ASC_Drive_Delay ASC_Drive_DelayStart ASC_ExternalTrigger ASC_GuestRoom:on,off ASC_LockOut:soft,hard,off ASC_LockOut_Cmd:inhibit,blocked,protection ASC_Mode_Down:absent,always,off,home ASC_Mode_Up:absent,always,off,home ASC_Open_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_Partymode:on,off ASC_Pos_Reading ASC_PrivacyDownValue_beforeNightClose ASC_PrivacyDown_Pos ASC_PrivacyUpValue_beforeDayOpen ASC_PrivacyUp_Pos ASC_RainProtection:on,off ASC_Roommate_Device ASC_Roommate_Reading ASC_Self_Defense_AbsentDelay ASC_Self_Defense_Mode:absent,gone,off ASC_Shading_InOutAzimuth ASC_Shading_MinMax_Elevation ASC_Shading_Min_OutsideTemperature ASC_Shading_Mode:absent,always,off,home ASC_Shading_Pos:10,20,30,40,50,60,70,80,90,100 ASC_Shading_StateChange_SunnyCloudy ASC_Shading_WaitingPeriod ASC_Shutter_IdleDetection ASC_ShuttersPlace:window,terrace ASC_Sleep_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_TempSensor ASC_Time_Down_Early ASC_Time_Down_Late ASC_Time_Up_Early ASC_Time_Up_Late ASC_Time_Up_WE_Holiday ASC_Up:time,astro,brightness,roommate ASC_Ventilate_Pos:10,20,30,40,50,60,70,80,90,100 ASC_Ventilate_Window_Open:on,off ASC_WiggleValue ASC_WindParameters ASC_WindProtection:on,off ASC_WindowRec
       HUEDevice65547 userattr ASC_Adv:on,off ASC_Antifreeze:off,soft,hard,am,pm ASC_Antifreeze_Pos:5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100 ASC_AutoAstroModeEvening:REAL,CIVIL,NAUTIC,ASTRONOMIC,HORIZON ASC_AutoAstroModeEveningHorizon:-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9 ASC_AutoAstroModeMorning:REAL,CIVIL,NAUTIC,ASTRONOMIC,HORIZON ASC_AutoAstroModeMorningHorizon:-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9 ASC_BlockingTime_afterManual ASC_BlockingTime_beforDayOpen ASC_BlockingTime_beforNightClose ASC_BrightnessSensor ASC_Closed_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_ComfortOpen_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_Down:time,astro,brightness,roommate ASC_DriveUpMaxDuration ASC_Drive_Delay ASC_Drive_DelayStart ASC_ExternalTrigger ASC_GuestRoom:on,off ASC_LockOut:soft,hard,off ASC_LockOut_Cmd:inhibit,blocked,protection ASC_Mode_Down:absent,always,off,home ASC_Mode_Up:absent,always,off,home ASC_Open_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_Partymode:on,off ASC_Pos_Reading ASC_PrivacyDownValue_beforeNightClose ASC_PrivacyDown_Pos ASC_PrivacyUpValue_beforeDayOpen ASC_PrivacyUp_Pos ASC_RainProtection:on,off ASC_Roommate_Device ASC_Roommate_Reading ASC_Self_Defense_AbsentDelay ASC_Self_Defense_Mode:absent,gone,off ASC_Shading_InOutAzimuth ASC_Shading_MinMax_Elevation ASC_Shading_Min_OutsideTemperature ASC_Shading_Mode:absent,always,off,home ASC_Shading_Pos:10,20,30,40,50,60,70,80,90,100 ASC_Shading_StateChange_SunnyCloudy ASC_Shading_WaitingPeriod ASC_Shutter_IdleDetection ASC_ShuttersPlace:window,terrace ASC_Sleep_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_TempSensor ASC_Time_Down_Early ASC_Time_Down_Late ASC_Time_Up_Early ASC_Time_Up_Late ASC_Time_Up_WE_Holiday ASC_Up:time,astro,brightness,roommate ASC_Ventilate_Pos:10,20,30,40,50,60,70,80,90,100 ASC_Ventilate_Window_Open:on,off ASC_WiggleValue ASC_WindParameters ASC_WindProtection:on,off ASC_WindowRec
       HUEDevice65556 userattr ASC_Adv:on,off ASC_Antifreeze:off,soft,hard,am,pm ASC_Antifreeze_Pos:5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100 ASC_AutoAstroModeEvening:REAL,CIVIL,NAUTIC,ASTRONOMIC,HORIZON ASC_AutoAstroModeEveningHorizon:-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9 ASC_AutoAstroModeMorning:REAL,CIVIL,NAUTIC,ASTRONOMIC,HORIZON ASC_AutoAstroModeMorningHorizon:-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9 ASC_BlockingTime_afterManual ASC_BlockingTime_beforDayOpen ASC_BlockingTime_beforNightClose ASC_BrightnessSensor ASC_Closed_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_ComfortOpen_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_Down:time,astro,brightness,roommate ASC_DriveUpMaxDuration ASC_Drive_Delay ASC_Drive_DelayStart ASC_ExternalTrigger ASC_GuestRoom:on,off ASC_LockOut:soft,hard,off ASC_LockOut_Cmd:inhibit,blocked,protection ASC_Mode_Down:absent,always,off,home ASC_Mode_Up:absent,always,off,home ASC_Open_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_Partymode:on,off ASC_Pos_Reading ASC_PrivacyDownValue_beforeNightClose ASC_PrivacyDown_Pos ASC_PrivacyUpValue_beforeDayOpen ASC_PrivacyUp_Pos ASC_RainProtection:on,off ASC_Roommate_Device ASC_Roommate_Reading ASC_Self_Defense_AbsentDelay ASC_Self_Defense_Mode:absent,gone,off ASC_Shading_InOutAzimuth ASC_Shading_MinMax_Elevation ASC_Shading_Min_OutsideTemperature ASC_Shading_Mode:absent,always,off,home ASC_Shading_Pos:10,20,30,40,50,60,70,80,90,100 ASC_Shading_StateChange_SunnyCloudy ASC_Shading_WaitingPeriod ASC_Shutter_IdleDetection ASC_ShuttersPlace:window,terrace ASC_Sleep_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_TempSensor ASC_Time_Down_Early ASC_Time_Down_Late ASC_Time_Up_Early ASC_Time_Up_Late ASC_Time_Up_WE_Holiday ASC_Up:time,astro,brightness,roommate ASC_Ventilate_Pos:10,20,30,40,50,60,70,80,90,100 ASC_Ventilate_Window_Open:on,off ASC_WiggleValue ASC_WindParameters ASC_WindProtection:on,off ASC_WindowRec
       HUEDevice65562 userattr ASC_Adv:on,off ASC_Antifreeze:off,soft,hard,am,pm ASC_Antifreeze_Pos:5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100 ASC_AutoAstroModeEvening:REAL,CIVIL,NAUTIC,ASTRONOMIC,HORIZON ASC_AutoAstroModeEveningHorizon:-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9 ASC_AutoAstroModeMorning:REAL,CIVIL,NAUTIC,ASTRONOMIC,HORIZON ASC_AutoAstroModeMorningHorizon:-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9 ASC_BlockingTime_afterManual ASC_BlockingTime_beforDayOpen ASC_BlockingTime_beforNightClose ASC_BrightnessSensor ASC_Closed_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_ComfortOpen_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_Down:time,astro,brightness,roommate ASC_DriveUpMaxDuration ASC_Drive_Delay ASC_Drive_DelayStart ASC_ExternalTrigger ASC_GuestRoom:on,off ASC_LockOut:soft,hard,off ASC_LockOut_Cmd:inhibit,blocked,protection ASC_Mode_Down:absent,always,off,home ASC_Mode_Up:absent,always,off,home ASC_Open_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_Partymode:on,off ASC_Pos_Reading ASC_PrivacyDownValue_beforeNightClose ASC_PrivacyDown_Pos ASC_PrivacyUpValue_beforeDayOpen ASC_PrivacyUp_Pos ASC_RainProtection:on,off ASC_Roommate_Device ASC_Roommate_Reading ASC_Self_Defense_AbsentDelay ASC_Self_Defense_Mode:absent,gone,off ASC_Shading_InOutAzimuth ASC_Shading_MinMax_Elevation ASC_Shading_Min_OutsideTemperature ASC_Shading_Mode:absent,always,off,home ASC_Shading_Pos:10,20,30,40,50,60,70,80,90,100 ASC_Shading_StateChange_SunnyCloudy ASC_Shading_WaitingPeriod ASC_Shutter_IdleDetection ASC_ShuttersPlace:window,terrace ASC_Sleep_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_TempSensor ASC_Time_Down_Early ASC_Time_Down_Late ASC_Time_Up_Early ASC_Time_Up_Late ASC_Time_Up_WE_Holiday ASC_Up:time,astro,brightness,roommate ASC_Ventilate_Pos:10,20,30,40,50,60,70,80,90,100 ASC_Ventilate_Window_Open:on,off ASC_WiggleValue ASC_WindParameters ASC_WindProtection:on,off ASC_WindowRec
       HUEDevice65565 userattr ASC_Adv:on,off ASC_Antifreeze:off,soft,hard,am,pm ASC_Antifreeze_Pos:5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100 ASC_AutoAstroModeEvening:REAL,CIVIL,NAUTIC,ASTRONOMIC,HORIZON ASC_AutoAstroModeEveningHorizon:-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9 ASC_AutoAstroModeMorning:REAL,CIVIL,NAUTIC,ASTRONOMIC,HORIZON ASC_AutoAstroModeMorningHorizon:-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9 ASC_BlockingTime_afterManual ASC_BlockingTime_beforDayOpen ASC_BlockingTime_beforNightClose ASC_BrightnessSensor ASC_Closed_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_ComfortOpen_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_Down:time,astro,brightness,roommate ASC_DriveUpMaxDuration ASC_Drive_Delay ASC_Drive_DelayStart ASC_ExternalTrigger ASC_GuestRoom:on,off ASC_LockOut:soft,hard,off ASC_LockOut_Cmd:inhibit,blocked,protection ASC_Mode_Down:absent,always,off,home ASC_Mode_Up:absent,always,off,home ASC_Open_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_Partymode:on,off ASC_Pos_Reading ASC_PrivacyDownValue_beforeNightClose ASC_PrivacyDown_Pos ASC_PrivacyUpValue_beforeDayOpen ASC_PrivacyUp_Pos ASC_RainProtection:on,off ASC_Roommate_Device ASC_Roommate_Reading ASC_Self_Defense_AbsentDelay ASC_Self_Defense_Mode:absent,gone,off ASC_Shading_InOutAzimuth ASC_Shading_MinMax_Elevation ASC_Shading_Min_OutsideTemperature ASC_Shading_Mode:absent,always,off,home ASC_Shading_Pos:10,20,30,40,50,60,70,80,90,100 ASC_Shading_StateChange_SunnyCloudy ASC_Shading_WaitingPeriod ASC_Shutter_IdleDetection ASC_ShuttersPlace:window,terrace ASC_Sleep_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_TempSensor ASC_Time_Down_Early ASC_Time_Down_Late ASC_Time_Up_Early ASC_Time_Up_Late ASC_Time_Up_WE_Holiday ASC_Up:time,astro,brightness,roommate ASC_Ventilate_Pos:10,20,30,40,50,60,70,80,90,100 ASC_Ventilate_Window_Open:on,off ASC_WiggleValue ASC_WindParameters ASC_WindProtection:on,off ASC_WindowRec
     Flower5D4A:
       HUEDevice65539 ASC_BrightnessSensor
       HUEDevice65556 ASC_BrightnessSensor
       HUEDevice65565 ASC_BrightnessSensor
     HM_36CD57:
       HUEDevice65544 ASC_WindowRec
     HM_4E1E2E:
       HUEDevice65539 ASC_WindowRec
     HM_718426:
       HUEDevice65562 ASC_WindowRec
     HUEDevice65539:
     HUEDevice65544:
     HUEDevice65547:
     HUEDevice65556:
     HUEDevice65562:
     HUEDevice65565:
     HmIP_SLO_000D5A49A83946:
       HUEDevice65539 ASC_BrightnessSensor
       HUEDevice65556 ASC_BrightnessSensor
       HUEDevice65565 ASC_BrightnessSensor
     sonnenstand:
       rolloControl ASC_twilightDevice
Attributes:
   ASC_autoAstroModeEvening REAL
   ASC_autoAstroModeMorning REAL
   ASC_expert 1
   ASC_tempSensor LuftMessung:temperature
   ASC_twilightDevice sonnenstand
   DbLogExclude .*
   alias      Rolladensteuerung
   devStateIcon { ShuttersControl_DevStateIcon($name) }
   icon       fts_shutter_automatic
   room       Intern__Cronjobs
   userattr   lightSceneParamsToSave lightSceneRestoreOnlyIfChanged:1,0

### Rollo
Internals:
   DEF        65556  IODev=IkeaTtradfri
   FUUID      5e8f1fd2-f33f-a573-26d2-f97bbdf85b42c2e5
   FVERSION   31_HUEDevice.pm:0.218370/2020-05-02
   ID         65556
   INTERVAL   
   IODev      IkeaTtradfri
   NAME       HUEDevice65556
   NR         522
   STATE      100
   TYPE       HUEDevice
   desired    1
   manufacturername IKEA of Sweden
   modelid    FYRTUR block-out roller blind
   name       K.L.Rollo
   power      Battery
   swversion  2.2.009
   type       blind
   uniqueid   
   OLDREADINGS:
   READINGS:
     2020-04-09 15:32:59   ASC_Enable      on
     2020-07-10 12:09:21   ASC_ShadingMessage INFO: current shading status is 'out' - next check in 10m
     2020-07-10 07:00:36   ASC_ShuttersLastDrive day open
     2020-07-10 07:00:02   ASC_Time_DriveDown 10.07.2020 - 21:26
     2020-07-10 07:00:02   ASC_Time_DriveUp 11.07.2020 - 09:00
     2020-07-09 19:38:26   associatedWith  rolloControl
     2020-07-09 19:38:27   battery         77
     2020-07-09 19:38:27   batteryPercent  77
     2020-07-10 07:00:36   pct             100
     2020-07-09 19:38:27   reachable       1
     2020-07-10 07:00:36   state           100
   helper:
     alert      
     battery    77
     bri        -1
     colormode  
     ct         -1
     devtype    
     effect     
     hue        -1
     mode       
     on         -1
     pct        100
     reachable  1
     rgb        
     sat        -1
     update_timeout 1
     xy         
     helper:
     json:
       id         65556
       manufacturername IKEA of Sweden
       modelid    FYRTUR block-out roller blind
       name       K.L.Rollo
       power      Battery
       r          lights
       swversion  2.2.009
       t          event
       type       blind
       uniqueid   
       config:
         battery    77
       state:
         pct        100
Attributes:
   ASC        2
   ASC_AutoAstroModeEvening REAL
   ASC_AutoAstroModeMorning REAL
   ASC_BrightnessSensor HmIP_SLO_000D5A49A83946:state
   ASC_LockOut off
   ASC_Partymode on
   ASC_Pos_Reading pct
   ASC_Shading_InOutAzimuth 135.00:290.00
   ASC_Shading_MinMax_Elevation 10.0:100.0
   ASC_Shading_Min_OutsideTemperature 29
   ASC_Shading_Mode always
   ASC_Shading_Pos 0
   ASC_Shading_StateChange_SunnyCloudy 10000:3000
   ASC_Shading_WaitingPeriod 1200
   ASC_ShuttersPlace window
   ASC_TempSensor LuftMessung:temperature
   ASC_Time_Down_Early 16:30
   ASC_Time_Down_Late 23:00
   ASC_Time_Up_Early 07:00
   ASC_Time_Up_Late 08:30
   ASC_Time_Up_WE_Holiday 09:00
   DbLogExclude .*
   IODev      IkeaTtradfri
   alias      K.L.Rollo
   color-icons 2
   devStateIcon 100:blinds-0 0:blinds-100 .*:blinds-50
   eventMap   /pct 100:on/ /pct 0:off/
   group      Heizung und Temperatur
   icon       fts_shutter
   lightSceneParamsToSave ASC_Shading_Mode
   model      FYRTUR block-out roller blind
   room       Kueche
   subType    blind
   userattr   ASC_Adv:on,off ASC_Antifreeze:off,soft,hard,am,pm ASC_Antifreeze_Pos:5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100 ASC_AutoAstroModeEvening:REAL,CIVIL,NAUTIC,ASTRONOMIC,HORIZON ASC_AutoAstroModeEveningHorizon:-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9 ASC_AutoAstroModeMorning:REAL,CIVIL,NAUTIC,ASTRONOMIC,HORIZON ASC_AutoAstroModeMorningHorizon:-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9 ASC_BlockingTime_afterManual ASC_BlockingTime_beforDayOpen ASC_BlockingTime_beforNightClose ASC_BrightnessSensor ASC_Closed_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_ComfortOpen_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_Down:time,astro,brightness,roommate ASC_DriveUpMaxDuration ASC_Drive_Delay ASC_Drive_DelayStart ASC_ExternalTrigger ASC_GuestRoom:on,off ASC_LockOut:soft,hard,off ASC_LockOut_Cmd:inhibit,blocked,protection ASC_Mode_Down:absent,always,off,home ASC_Mode_Up:absent,always,off,home ASC_Open_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_Partymode:on,off ASC_Pos_Reading ASC_PrivacyDownValue_beforeNightClose ASC_PrivacyDown_Pos ASC_PrivacyUpValue_beforeDayOpen ASC_PrivacyUp_Pos ASC_RainProtection:on,off ASC_Roommate_Device ASC_Roommate_Reading ASC_Self_Defense_AbsentDelay ASC_Self_Defense_Mode:absent,gone,off ASC_Shading_InOutAzimuth ASC_Shading_MinMax_Elevation ASC_Shading_Min_OutsideTemperature ASC_Shading_Mode:absent,always,off,home ASC_Shading_Pos:10,20,30,40,50,60,70,80,90,100 ASC_Shading_StateChange_SunnyCloudy ASC_Shading_WaitingPeriod ASC_Shutter_IdleDetection ASC_ShuttersPlace:window,terrace ASC_SlatPosCmd_SlatDevice ASC_Sleep_Pos:0,10,20,30,40,50,60,70,80,90,100 ASC_TempSensor ASC_Time_Down_Early ASC_Time_Down_Late ASC_Time_Up_Early ASC_Time_Up_Late ASC_Time_Up_WE_Holiday ASC_Up:time,astro,brightness,roommate ASC_Ventilate_Pos:10,20,30,40,50,60,70,80,90,100 ASC_Ventilate_Window_Open:on,off ASC_WiggleValue ASC_WindParameters ASC_WindProtection:on,off ASC_WindowRec ASC_WindowRec_PosAfterDayClosed:open,lastManual ASC_WindowRec_subType:twostate,threestate lightSceneParamsToSave lightSceneRestoreOnlyIfChanged:1,0 room_map structexclude
   webCmd     on:off
   widgetOverride on:uzsuSelect,auf off:uzsuSelect,zu

**Comment by lordofweb19** [comment]
Duplikat zu 
https://github.com/fhem/AutoShuttersControl/issues/75 
https://github.com/fhem/AutoShuttersControl/issues/74
?

**Comment by CoolTuxNet** [comment]
sollte in der aktuellen Version behoben sein, bitte beobachten.
