### ISSUE TITLE
Immer wiederkehrendes Fahren, da Rollladen blockiert.

### ISSUE THREAD

**Issue by pc1246** [fhem/AutoShuttersControl#76]
Moin
Siehe auch hier: https://forum.fhem.de/index.php/topic,112325.msg1072127.html#msg1072127
Es passiert bei meinen Dachfensterrolllaeden des oefteren, dass diese gegen ein offenes Fenster fahren. Leider mag ASC das partout nicht leiden und versucht immer wieder zu fahren. Das sollte unbedingt abstellbar sein, damit die Rolllaeden, oder das was dazwischen ist, keinen Schaden nimmt.
Ich denke ASC will es an der Stelle zu genau machen, und vergleicht die Soll- mit der Istposition. Ein manueller Stopp waere ja auch ein aehnlicher Fall, und wuerde wahrscheinlich nicht erkannt werden, und eine erneute Fahrt ausloesen!?
Gruss Christoph

**Comment by CoolTuxNet** [comment]
Worauf bezieht sich die wiederkehrende Fahrt genau. Denn eigentlich ist es ASC egal, es sendet einmalig einen Fahrbefehl und das war es. Bei der Beschattung wird natürlich geschaut ob aktuelle Pos = ShadingPos ist und wenn nicht wird versucht da Beschattung aktiv in die ShadingPos zu fahren. Aber das kann ich nicht beeinflussen. Eventuell wäre hier ein Fensterkontakt gut.
