### ISSUE TITLE
Rain protection fährt Markisen ständig auf und zu

### ISSUE THREAD

**Issue by phoenix-anasazi** [fhem/AutoShuttersControl#78]
Hallo Marko,

ich hatte das Problem schonmal im Forum gepostet, leider hat das letzte Update nichts geändert:

Wenn meine Markisen auf Shading-In oder auch manuell ausgefahren sind und der Regensensor Regen meldet (sendet minütlich 1 bei Regen), fährt die Markise zwar korrekt ein, aber nach einer Minute wieder zurück. Im ASC Debug kommt dann rain un-protected, obwohl der Regensensor immer noch auf 1, also "Regen erkannt" steht. Last drive bleibt die ganze Zeit auf manual (Das ist, glaube ich, ein anderes Thema, da bei mir die Last drives fast nie aktualisiert werden).
{ ascAPIget('RainProtectionStatus','EGMarkWGsued') } wechselt dabei ständig zwischen protected und unprotected, obwohl der Regensensor durchgehend (minütlich) 1, also Regen, meldet. 

Definition Regensensor:
>    ASC_rainSensor DUOFERN_690DF4_sensor:isRaining 0 100

Danke und Grüße
Sascha

**Comment by LeonGaultier** [comment]
Hallo Sascha,

Wieso steht bei Dir 0 100, Wenn 1 sagt das es Regnet dann muss es heißen 1 100

**Comment by CoolTuxNet** [comment]
Ich habe es eben in meiner Umgebung getestet und konnte das Verhalten leider nicht nach stellen. Bei mir arbeitet das Rollo korrekt.

Ist das Zufällig ein Multisensor?

**Comment by phoenix-anasazi** [comment]
Hallo Leon, 

CoolTux hat im Forum gesagt, dass es 0 100 sein muss, weil auf größer X geprüft wird. Ja, ist ein Multisensor. Funktioniert aber auch nicht, wenn nur der Regen bzw. Wind-Wert genommen wird. Ich bin inzwischen von ASC weg, hat sich für mich im Prinzip erledigt.
