### ISSUE TITLE
Zeitangaben ohne Tagesnummer bei verschiedenen Perl-Varianten

### ISSUE THREAD

**Issue by Nobby1805** [fhem/AutoShuttersControl#79]
Beispiel
     2019-09-01 19:43:14   ASC_Time_DriveDown .09.2019 - 19:56
     2019-09-01 19:43:14   ASC_Time_DriveUp .09.2019 - 07:55

s. auch ASC ... was muss mindestens definiert werden #26 

Looking perldoc POSIX, it says

#-----------------
If you want your code to be portable, your format (fmt ) argument should
use only the conversion specifiers defined by the ANSI C standard (C89,
to play safe). These are aAbBcdHIjmMpSUwWxXyYZ%.
#------------------

so that would tell you that "%e %T" may not be portable.

**Comment by CoolTuxNet** [comment]
fix in 0.10.7
