### ISSUE TITLE
associatedWith verwenden

### ISSUE THREAD

**Issue by rejoe2** [fhem/AutoShuttersControl#8]
Evtl. beim Verteilen der Attribute in den Rollladen-Devices ein Reading "associatedWith" mit dem Namen des ASC-Modul-Devices als Inhalt setzen bzw. ein vorhandenes ergänzen.

Damit erscheint unten in der Detailansicht des Rollladen-Geräts jeweils ein Link zum ASC-Device, und dieses wird bei list -R mit ausgegeben.

**Comment by LeonGaultier** [comment]
seit Version 0.6.3 vorhanden
