### ISSUE TITLE
Fenster kippen vor DayOpen

### ISSUE THREAD

**Issue by CoolTuxNet** [fhem/AutoShuttersControl#8]
Habe gestern und heute morgen eine kleine Merkwürdigkeit festgestellt, und zwar wenn ich vorm Day Open ein Fenster kippe dann wir in Ventialte Position gefahren. Das Fenster bleibt dann gekippt über das Day Open hinweg und die Rolllade fährt auch hoch. Wenn jetzt das Fenster geschlossen wird fährt die Rolllade aber wieder komplett zu und das ASC Device schreibt window night closed. Das passiert bei einen Fenster mit Brightness sowie mit Astro.
ASC Version ist 0.4.0.2 mit der Git version habe ich es noch nicht ausprobiert.

**Comment by CoolTuxNet** [comment]
So heute morgen konnte ich es reproduzieren. Es scheint so das wenn das Rollo (diesmal mit Brightness) gekippt ist und dann geöffnet wird durch ASC und nach dem Öffnen geschlossen wird innerhalb der ASC_Time_Up_Early und ASC_Time_Up_Late Zeit, fährt es runter mit window night closed. Ich denke das wird auch bei den Astro Rollos so sein werde das morgen früh testen.
Was mir bei Brightness noch aufgefallen ist das die Zeit ASC_Time_Up_WE_Holiday nicht berücksichtigt wird, bei Astro funktioniert es wunderbar. Sollte nicht bei Brightness am Wochenende die Zeit ASC_Time_Up_Early mit ASC_Time_Up_WE_Holiday ersetzt werden?

**Comment by CoolTuxNet** [comment]
Das liegt daran das sich an der ASC_Time_Up_Late Zeit orientiert wird und somit vor ASC_Time_Up_Late für das Modul noch Nacht ist. Es muß zusätzlich abgefragt werden ob Brightness Max am Morgen erreicht wurde. Das selbe gilt für Abends

**Comment by LeonGaultier** [comment]
fix wurde zum testen bereit gestellt
