### ISSUE TITLE
Perl Fehlermeldung bei getAntiFreezeStatus

### ISSUE THREAD

**Issue by Nobby1805** [fhem/AutoShuttersControl#80]
2020.07.18 09:13:21.825 1: PERL WARNING: Argument "" isn't numeric in numeric lt (<) at lib/FHEM/Automation/ShuttersControl/Shutters.pm line 533.

Die Abfrage sieht komisch aus, entweder fehlt da etwas oder ich verstehe mal wieder eine komplexe Perl-Struktur nicht

**Comment by CoolTuxNet** [comment]
Kannst Du mir die Zeile in der aktuellen Version geben. 0.10.6

**Comment by Nobby1805** [comment]
Ich möchte aus diversen Gründen z.Zt. keinen Update des Fhem machen ... vielleicht helfen dir folgende Infos

73_AutoShuttersControl.pm 22366 2020-07-07 08:54:34Z CoolTux

FVERSION | 73_AutoShuttersControl.pm:v0.10.3-s22366/2020-07-07 TESTING

529 sub getAntiFreezeStatus {
530    use POSIX qw(strftime);
531    my $self = shift;
532    my $daytime = strftime( "%P", localtime() );
533    $daytime = (
534        defined($daytime) && $daytime
535        ? $daytime
536        : ( strftime( "%k", localtime() ) < 12 ? 'am' : 'pm' )
537    );
538    my $outTemp = $FHEM::Automation::ShuttersControl::ascDev->getOutTemp;

**Comment by CoolTuxNet** [comment]
Kannst Du bitte folgenden Befehl in die Kommandozeile von FHEMWEB eingeben und mir sagen was Du als Antwort bekommst
`{ strftime( "%k", localtime() ) }`

Auf welchen System läuft FHEM bei Dir?

**Comment by Nobby1805** [comment]
Da kommt gar nichts !?!

FHEM: 5.9 auf Windows Server 2003 mit Strawberry Perl 5.26.1.1-32bit

**Comment by CoolTuxNet** [comment]
Dann ist das das Problem. Ich habe kein Windows und kann demzufolge Perl damit nicht testen.
Ich kann Dir nur empfehlen auf Linux umzusteigen. Es tut mir Leid.

**Comment by Nobby1805** [comment]
müsste die Abfrage mit %H nicht ebenso funktionieren?

**Comment by CoolTuxNet** [comment]
Bei mir geht es mit %H und bei Dir?

**Comment by Nobby1805** [comment]
%H klappt, da kommt jetzt um 10:53 eine 10

**Comment by CoolTuxNet** [comment]
Ok dann ändere ich das und hoffe mal das es keine Nebenwirkungen hat.
