### ISSUE TITLE
Use dusk and dawn functions of Rademacher

### ISSUE THREAD

**Issue by biggbang** [fhem/AutoShuttersControl#87]
I have Rademacher shutters and I am using at definitions to control these shutters. I use the set function of DUOFERN: `set <name> dusk/dawn` to shut or open all shutters, but only those which are in dusk/dawn mode by the shutter switch.
As I've understood, shutting down or opening by ACS works by setting the position regardless which mode is set. Could you please add this functionalityor could you point me to the code where such functionality belongs? I would try to change this to my requirements. Thanks in advance! Mathias

**Comment by CoolTuxNet** [comment]
The functionality of ASC is based exclusively on numerical values in the driving instructions and the position evaluation.
