### ISSUE TITLE
IsAfterShuttersTimeBlocking() ohne fhem::Automation::ShuttersControl::Helper::IsAfterShuttersTimeBlocking

### ISSUE THREAD

**Issue by FunkOdyssey2001** [fhem/AutoShuttersControl#89]
https://github.com/fhem/AutoShuttersControl/blob/d1b04fcdce150c7f66fd0a231cfe0cce39661712/lib/FHEM/Automation/ShuttersControl/EventProcessingFunctions.pm#L580

Hallo,
ich kenne mich mit OOP nicht wirklich gut aus, aber ist in dieser PM evtl. der Funktionsaufruf nicht korrekt?

Müsste es dort auch "fhem::Automation::ShuttersControl::Helper::IsAfterShuttersTimeBlocking()" heißen?
Überall?

**Comment by FunkOdyssey2001** [comment]
Ich nehme an, dass ich falsch liege. 
Vermutlich legitimiert die Zeile "use FHEM::Automation::ShuttersControl::Helper qw (:ALL);" alles weitere.

**Comment by CoolTuxNet** [comment]
So schaut es aus. Und wenn man sich im Packagefile FHEM::Automation::ShuttersControl::Helper den Export von ALL anschaut sieht man das dort dann auch :IsAfterShuttersTimeBlocking mit drin steht :-)
